### PR TITLE
JSON, Warning and Recursive File support

### PR DESCRIPTION
**Pull request by bsobe**
We couldn't generate the report because the file reader couldn't find metric files in child folders. 
That's why, I added the support for searching metric files in child folders. 

I also added a new reporting type called "Warning" because while working on a large project, the reports can be really long. 
I tried to simplify the report.

Lastly, I added support for formatted JSON reports. I think it can be really useful while working on CLI.

### CODE REVIEW

**Comment by jayasuryat** [comment]
Hi @bsobe! 👋
Thanks for the fixes and new additions.

Looks like you guys have put in a lot of effort. Almost 1500 new lines.

I just wanted to let you know that I'll need a bit of time to go through everything and make sure I understand the changes fully. Once I've had a chance to review it all, I'll get back to you as soon as possible.

**Comment by jayasuryat** [comment]
Hey @bsobe, could please check and fix the failing test.

**Comment by bsobe** [comment]
> Hey @bsobe, could please check and fix the failing test.

Thanks for your quick action and review. 

I am going to fix it as soon as possible. 
Did you encounter any problems other than tests?

**Comment by jayasuryat** [comment]
I have went through the changes you made @bsobe, and I must say, I am happy with them. 😊 

There are just a few things that I wanted to ask you about, just to make sure I understand your intentions correctly. These are minor things about conventions and such.

1. I see you’ve defined `ExportType.find(**)` & ``ReportType.find(**)` methods by hand. Every `Enum` by default already has a `Enum.valueOf("name")` method. So we could do `ExportType.valueOf("HTML")`. Any reason why you prefer the former way?, or this is also fine with you?
2. Any reason as to why `totalModules` variable in `ComposablesReport` class has been moved into constructor and renamed?
3. And any particular reason why you moved `Overview` model into a new file?
4. The new `reportType` CLI argument name’s is a little bit confusing to me. As soon I saw it for the first time, I thought, well the report only exports warnings, so what this might mean. Then, when I went thought the code then I understood, `ReportType.FULLY` meant all modules (regardless of if they have any _mendable_ composables or not) should be included in the report. And `ReportType.WARNINGS` meant only modules which had _mendable_ composables were included. I thought for this `includeModules` would be a more appropriate name with enum options being `IncludeModules.ALL` and `IncludeModules.WITH_WARNINGS`. I felt it more accurately encapsulated the intensions.


Let me know how you feel about these, we can further discuss and make changes if needed.

**Comment by bsobe** [comment]
> I have went through the changes you made @bsobe, and I must say, I am happy with them. 😊
> 
> There are just a few things that I wanted to ask you about, just to make sure I understand your intentions correctly. These are minor things about conventions and such.
> 
> 1. I see you’ve defined `ExportType.find(**)` & `ReportType.find(**)` methods by hand. Every `Enum` by default already has a `Enum.valueOf("name")` method. So we could do `ExportType.valueOf("HTML")`. Any reason why you prefer the former way?, or this is also fine with you?
> 2. Any reason as to why `totalModules` variable in `ComposablesReport` class has been moved into constructor and renamed?
> 3. And any particular reason why you moved `Overview` model into a new file?
> 4. The new `reportType` CLI argument name’s is a little bit confusing to me. As soon I saw it for the first time, I thought, well the report only exports warnings, so what this might mean. Then, when I went thought the code then I understood, `ReportType.FULLY` meant all modules (regardless of if they have any _mendable_ composables or not) should be included in the report. And `ReportType.WARNINGS` meant only modules which had _mendable_ composables were included. I thought for this `includeModules` would be a more appropriate name with enum options being `IncludeModules.ALL` and `IncludeModules.WITH_WARNINGS`. I felt it more accurately encapsulated the intensions.
> 
> Let me know how you feel about these, we can further discuss and make changes if needed.

Thanks for your kindness. 
Let me explain: 
1. `Enum::valueOf` compares strings exactly to find the instance. 
I mean if the user enters "html" instead of "HTML", the function called valueOf does not return ExportType.HTML. 
Therefore, I pass the true as `ignoreCase` parameters to `String::equals` function in `ExportType::find`.

2. First of all, I think that name of the variable called `totalModules` is not right. 
It represents the count of total modules. That's why, I changed it. 
However, if you think this is not the best name or this name is not correct too, I would like to rename it.
The second part is related to moving the variable into the constructor. 
Before my change, the value of `totalModules` equals the count of `moduleReports`. 
However, I added a new parser called `WarningReportParser`. This class helps us to filter modules if the value of `skippablePercentage` equals 100. 
So, if we use `WarningReportParser` instead of `FullyReportParser`, the count of modules is affected because of filter operation.
However, we processed the same count of modules, it should not change. 
That's why, instead of assigning the value of `totalModules` automatically (the size of the list), I moved it into the constructor and passed the value of the processed module count.
This explanation is a little bit long but I hope I explained it well. 

3. There is no good explanation for this change. Should I revert it? 

4. I think I can not understand the point. 
Before asking for details, I would like to share the differences between `Fully` and `Warning`. 
`Fully` works the same as your implementation. There is not any change.
However, `Warning` filters the report of the module if the skippablePercentage equals 100 // WarningReportParser::31
In the end, the report does not contain any information about the module if there is not any unstable method in it.
Now, to understand what you mention, 
do you think that the name of reporter types can be confusing?
or 
can you tell me again which part you want me to change|rename?

**Comment by bsobe** [comment]
Also, sorry to say this but I think the failing test is flaky.
I ran the tests locally and there are no errors.

This is my first time working with GitHub Actions.
So, do you have or can you get reports of failed test details that contain information about expected result and the actual result

**Comment by jayasuryat** [comment]
Hey @bsobe, so the issue seems to be with `JsonArray` element **ordering**. You can look [here](https://github.com/jayasuryat/mendable/actions/runs/4745820087/jobs/8428661471) for the logs and context.

Even tho the two objects are structurally equal, their array elements order is not same. That is what is causing the test to fail.

And I don't know what is causing the sorting order of the elements to change, they are working fine locally for me as well. Seems like some weird environment configuration issue. 

That being said, moving away from such a non-deterministic check would be better for us as well.

Need to see how to compare two JSONs structurally, ignoring their sorting order.

**Comment by jayasuryat** [comment]
@bsobe, I've fixed the issue with the test case. And as I had suspected, it is an issue with `JsonArray` element ordering.


---

And thanks for clarifying about my questions
1. Yes, `Enum::valueOf` is a little bit more strict than maybe required. On the other hand, the current implementation is a little bit too _forgiving_. Any param that does not match, straight goes to the `else block` and get coerced into `ReportType.FULLY` or `ExportType.JSON` respectively. I think it should only compare `equality` (while ignoring case) and `throw exception` if no match is found. Something like :  
```kotlin
ExportType.values().firstOrNull { entry: ExportType ->
    entry.name.equals(type, ignoreCase = true)
} ?: error(
    "$type does not match with any entries of enum `${ExportType::class.java.canonicalName}`." +
            " Valid choices are ${ExportType.values().map { it.name }}"
)
```
2. Now I got your intentions correctly. I think we should add these two as two separate `parameters` in the class. It is useful information for the user, and adds a bit of clarity. Maybe we can add these two as `totalModulesScanned` and `totalModulesReported`. Feel free to suggest better names.
3. No worries, please do.
4. My understanding of `Fully` and `Warning` aligns with your explanation. I was just suggesting `IncludeModules.ALL` & `IncludeModules.WITH_WARNINGS` were more descriptive names for what they represented.

Again, let me know how you feel about these.

**Comment by bsobe** [comment]
> @bsobe, I've fixed the issue with the test case. And as I had suspected, it is an issue with `JsonArray` element ordering.
> 
> And thanks for clarifying about my questions
> 
> 1. Yes, `Enum::valueOf` is a little bit more strict than maybe required. On the other hand, the current implementation is a little bit too _forgiving_. Any param that does not match, straight goes to the `else block` and get coerced into `ReportType.FULLY` or `ExportType.JSON` respectively. I think it should only compare `equality` (while ignoring case) and `throw exception` if no match is found. Something like :
> 
> ```kotlin
> ExportType.values().firstOrNull { entry: ExportType ->
>     entry.name.equals(type, ignoreCase = true)
> } ?: error(
>     "$type does not match with any entries of enum `${ExportType::class.java.canonicalName}`." +
>             " Valid choices are ${ExportType.values().map { it.name }}"
> )
> ```
> 
> 2. Now I got your intentions correctly. I think we should add these two as two separate `parameters` in the class. It is useful information for the user, and adds a bit of clarity. Maybe we can add these two as `totalModulesScanned` and `totalModulesReported`. Feel free to suggest better names.
> 3. No worries, please do.
> 4. My understanding of `Fully` and `Warning` aligns with your explanation. I was just suggesting `IncludeModules.ALL` & `IncludeModules.WITH_WARNINGS` were more descriptive names for what they represented.
> 
> Again, let me know how you feel about these.

1. Great. Throwing an exception and giving information to the user is a good idea. 
2. The names that you suggest are good. Just I suggest we can add another parameter called `totalModulesFiltered` to give information about filtered modules to the user.
3. I'm going to change it as soon as possible. 
4. I got it. Yes, I agree with you. `IncludeModules` is better.

**Comment by jayasuryat** [comment]
Sure, you can make these changes at your earliest convenience.

So here, `totalModulesFiltered` would equal to `totalModulesScanned` - `totalModulesReported`, right?

**Comment by jayasuryat** [comment]
Hey @bsobe, got any update on this?

**Comment by jayasuryat** [comment]
Hey @bsobe! 👋

It seems like we've lost touch since the last time. 

But I'm still interested in including your contributions in the project. So, I've decided to make the changes myself, ensuring your original ideas are properly implemented. 

I really appreciate the effort you put into submitting the pull request. I'll make sure to give you credit for your initial contribution once the changes are done. 

If you have any more suggestions or insights about your original submission, or any new changes, feel free to let me know.

**Review by jayasuryat — APPROVED** [review]

**Pull request merged**
